Remove satellite6-pulp-trigger job
Integrate the steps from satellite6-pulp-trigger onto
satellite6-pulp-automation job. Now all output will be available on a single
console output.

diff --git a/ci/jobs/satellite6-pulp.yaml b/ci/jobs/satellite6-pulp.yaml
--- a/ci/jobs/satellite6-pulp.yaml
+++ b/ci/jobs/satellite6-pulp.yaml
@@ -1,3 +1,105 @@
+# The macro to trigger remote Jenkins Jobs by satellite-pulp test.
+# The {TRIGGER_TYPE} can either be 1) "installation", to trigger satellite6-installer, or
+# 2) "robottelo", to trigger satellite6-standalone-automation job.
+- builder:
+    name: satellite6-pulp-macro
+    builders:
+        - shining-panda:
+            build-environment: virtualenv
+            name: satellite6-pulp-trigger
+            python-version: System-CPython-2.7
+            nature: shell
+            command: |
+                pip install -U pip
+                pip install requests
+        - shining-panda:
+            build-environment: virtualenv
+            name: satellite6-pulp-trigger
+            python-version: System-CPython-2.7
+            nature: python
+            command: |
+                from __future__ import print_function
+                import logging
+                import os
+                import pip
+                import pprint
+                import requests
+                import sys
+                import time
+
+                JENKINS_URL = os.environ.get('REMOTE_JENKINS_URL')
+                JENKINS_API_TOKEN = os.environ.get('REMOTE_JENKINS_API_TOKEN')
+                JENKINS_USERNAME = os.environ.get('REMOTE_JENKINS_USERNAME')
+                # Change the remote job name here.
+                trigger_type = "{TRIGGER_TYPE}"
+                if trigger_type == 'installation':
+                    remote_job_name = 'satellite6-installer'
+                elif trigger_type == 'robottelo':
+                    remote_job_name = 'satellite6-standalone-automation'
+                else:
+                    print('The job has failed because the trigger type cannot be recognized.')
+                    print(
+                        'Available trigger types are: 1) installation, to trigger '
+                        'satellite6-installer job; 2) robottelo, to trigger '
+                        'satellite6-standalone-automation job.'
+                    )
+                    sys.exit(1)
+
+                logging.captureWarnings(True)
+                print('Get crumb from Satellite Jenkins server...')
+                crumb = requests.get(
+                    JENKINS_URL + '/crumbIssuer/api/json',
+                    auth=(JENKINS_USERNAME, JENKINS_API_TOKEN),
+                    verify=False
+                ).json()
+                print('Trigger the remote Jenkins job {{}}...'.format(remote_job_name))
+
+                queue_url = requests.post(
+                    JENKINS_URL + '/job/{{}}/buildWithParameters'
+                    .format(remote_job_name),
+                    auth=(JENKINS_USERNAME, JENKINS_API_TOKEN),
+                    data={{
+                        'SERVER_HOSTNAME': os.environ.get('INSTANCE_IP'),
+                        'DISTRIBUTION': "{DISTRIBUTION}",
+                        'SATELLITE_RELEASE': "{SATELLITE_RELEASE}",
+                        'SATELLITE_VERSION': "{SATELLITE_VERSION}",
+                        'SETUP_FAKE_MANIFEST_CERTIFICATE': True,
+                        'TEST_TYPE': "{SATELLITE_TEST_TYPE}",
+                        'REMOTE_JENKINS_USERNAME': os.environ.get('REMOTE_JENKINS_USERNAME'),
+                        'REMOTE_JENKINS_API_TOKEN': os.environ.get('REMOTE_JENKINS_API_TOKEN'),
+                        'REMOTE_JENKINS_URL': os.environ.get('REMOTE_JENKINS_URL'),
+                        crumb['crumbRequestField']: crumb['crumb']
+                    }},
+                    verify=False
+                ).headers['Location']
+
+                time.sleep(5)
+                queue = requests.get(queue_url + '/api/json', verify=False).json()
+                while not queue.get('executable'):
+                    time.sleep(1)
+                    queue = requests.get(queue_url + '/api/json', verify=False).json()
+                print('Job #{{0}} ({{1}}) was triggered...'.format(
+                    queue['executable']['number'],
+                    queue['executable']['url']
+                ))
+
+                result = None
+                while result is None:
+                    time.sleep(1)
+                    response = requests.get(
+                        JENKINS_URL + '/job/{{0}}/{{1}}/api/json'
+                        .format(
+                            remote_job_name,
+                            queue['executable']['number']
+                        ),
+                        verify=False
+                    ).json()
+                    result = response.get('result')
+                    if result:
+                        pprint.pprint(result)
+
+
+
 # This job automates the process of deploying Satellite 6 on OpenStack instances
 # and upgrading the Pulp for Robottelo and Pulp Smash tests.
 # Prerequisites:
@@ -99,8 +201,14 @@
                 --security-groups $SECURITY_GROUP_NAME \
                 $INSTANCE_NAME
             INSTANCE_IP=""
+            COUNTER=1
             while [[ -z "${INSTANCE_IP}" ]]; do
-                echo "The network is not yet ready..."
+                echo "The network is not yet ready ${COUNTER} times..."
+                let COUNTER+=1
+                if [[ ${COUNTER} -gt 50 ]]; then
+                    echo "The OpenStack instance was failed to create..."
+                    exit 1
+                fi
                 sleep 1
                 INSTANCE_IP="$(nova list | grep ${INSTANCE_NAME} | awk {' print $13 '} | head -1)"
             done
@@ -125,6 +233,7 @@
             # Wait until the OpenStack instance can be connected by SSH sessions.
             # The following trigger builders will depend on SSH connectivity.
             set +e
+            COUNTER=0
             while true; do
                 ssh -o ConnectTimeout=5 \
                     -o StrictHostKeyChecking=no \
@@ -132,40 +241,30 @@
                 if [[ $? = 0 ]]; then
                     break
                 fi
-                echo "$INSTANCE_IP is not yet ready...";
+                let COUNTER+=1
+                echo "${INSTANCE_IP} is not yet ready for ${COUNTER} times...";
                 sleep 5
             done
             set -e
-        - trigger-builds:
-            - project: "satellite6-pulp-trigger"
-              block: true
-              bool-parameters:
-                  - name:  SETUP_FAKE_MANIFEST_CERTIFICATE
-                    value: true
-              predefined-parameters: |
-                  TRIGGER_TYPE=installation
-                  SERVER_HOSTNAME=${INSTANCE_IP}
-                  DISTRIBUTION=DOWNSTREAM
-                  SATELLITE_VERSION=6.2
-                  SATELLITE_RELEASE=GA
-                  REMOTE_JENKINS_USERNAME=${REMOTE_JENKINS_USERNAME}
-                  REMOTE_JENKINS_API_TOKEN=${REMOTE_JENKINS_API_TOKEN}
-                  REMOTE_JENKINS_URL=${REMOTE_JENKINS_URL}
+        - satellite6-pulp-macro:
+            # Generic macro call for satellite6-installer
+            TRIGGER_TYPE: "installation"
+            DISTRIBUTION: "DOWNSTREAM"
+            SATELLITE_RELEASE: "GA"
+            SATELLITE_VERSION: "6.2"
+            SATELLITE_TEST_TYPE: ""
         - trigger-builds:
             - project: "satellite6-pulp-upgrade"
               block: true
               predefined-parameters: |
                   INSTANCE_IP=${INSTANCE_IP}
-        - trigger-builds:
-            - project: "satellite6-pulp-trigger"
-              block: true
-              predefined-parameters: |
-                  TRIGGER_TYPE=robottelo
-                  SERVER_HOSTNAME=${INSTANCE_IP}
-                  TEST_TYPE=endtoend-api
-                  REMOTE_JENKINS_USERNAME=${REMOTE_JENKINS_USERNAME}
-                  REMOTE_JENKINS_API_TOKEN=${REMOTE_JENKINS_API_TOKEN}
-                  REMOTE_JENKINS_URL=${REMOTE_JENKINS_URL}
+        - satellite6-pulp-macro:
+            # Generic macro call for satellite6-standalone-automation
+            TRIGGER_TYPE: "robottelo"
+            SATELLITE_TEST_TYPE: "endtoend-api"
+            DISTRIBUTION: ""
+            SATELLITE_RELEASE: ""
+            SATELLITE_VERSION: ""
         - shell: |
             echo ${REMOTE_JENKINS_USERNAME}
             source sat-pulp/bin/activate
@@ -173,3 +272,4 @@
             if [[ ! -z "$(nova list | grep ${INSTANCE_ID})" ]]; then
                nova delete $INSTANCE_ID
             fi
+
